config/routes.rb
Rails.application.routes.draw do
  root 'first#home'
  get '/singup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/attendances_now', to: 'users#attendances_now', as: :attendances_now
  patch 'users/:id/attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime #残業申請
  patch 'users/:id/attendances/:id/update_month', to: 'attendances#update_month', as: :update_month #所属長申請
  get 'users/:id/attendances/:id/receive_overtime', to: 'attendances#receive_overtime', as: :receive_overtime#残業申請のお知らせ
  patch 'users/:id/attendances/:id/update_receive', to: 'attendances#update_receive', as: :update_receive #~申請のお知らせ(update)
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances#勤怠を編集
  get 'users/:id/attendances/:date/atlog', to: 'attendances#atlog', as: :atlog#勤怠修正ログ
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances#勤怠を編集(update)
  get 'users/:id/attendances/:id/receive_attendance', to: 'attendances#receive_attendance', as: :receive_attendance #勤怠変更のお知らせ
  patch 'users/:id/attendances/:id/update_receive_attendance', to: 'attendances#update_receive_attendance', as: :update_receive_attendance #勤怠変更のお知らせ
  get 'users/:id/attendances/:id/receive_month', to: 'attendances#receive_month', as: :receive_month#所属長承認のお知らせ
  
  resources :users do
    resources :attendances
  end
  
  resources :bases
  
  resources 'users', only: :index do
    collection { post :import }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  before_save {self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: {minimum: 6 },allow_nil: true
  
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      obj = new
      obj.attributes = row.to_hash.slice(*updatable_attributes)

      obj.save!
    end
  end

  def self.updatable_attributes
    ["name","email","belongs","code","card_id",
    "password","password_confirmation",
    "basic_time","work_time","finish_time","admin","instructor"]
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index,:show,:edit,:update,:destroy]
  before_action :admin_user, only: [:destroy,:edit_basic_info,:update_basic_info,:attendances_now,:index]
  before_action :correct_user, only: [:show,:edit,:update]
  before_action :admin_user_show, only: [:show]
  
  def show
    @user = User.find(params[:id])
    @users = User.all
    @count_overtime = Attendance.where(instructor_name: current_user.id).where.not(over_time: nil).where(approval: "申請中").count 
    @count_attendance = Attendance.where(instructor_nameat: current_user.id).where.not(started_be: nil).where(approval_at: "申請中").count 
    @count_month = Attendance.where(instructor_namemo: current_user.id).where(approval_mo: "申請中").count 
    @instructor = User.where(instructor: true)
    if params[:ftime].nil?
      @ftime = Date.today.beginning_of_month
    else
      @ftime = Date.parse(params[:ftime])
    end
    @ltime = @ftime.end_of_month
    (@ftime..@ltime).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
    @worked_sum = @dates.where.not(started_at: nil).count
  end
  
    
  
  def index
    @users = User.all
  end
  
  def import
    User.import(params[:file])
    redirect_to root_url
    return
  end
  
  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to users_url 
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "ユーザの新規作成に成功しました。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def edit_basic_info
    @user = User.find(params[:id])
  end
  
  def update_basic_info
    @user = User.find(params[:id])
    if @user.update_attributes(basic_info_params)
        flash[:success] = "基本情報を更新しました。"
        redirect_to @user
    else
      render 'edit_basic_info'
    end
  end
  
  def attendances_now
    @users = User.all
  end
  
  
  
  private
  
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:belongs,:code,:basic_time,:work_time,:finish_time,:card_id)
  end
  
  def basic_info_params
    params.require(:user).permit(:basic_time,:work_time)
  end
  
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] ="ログインしてください"
      redirect_to login_url
    end
  end
  
  def correct_user
   
    @user = User.find_by(id: params[:id]) 
    unless current_user?(@user) || current_user.admin? || current_user.instructor?
      flash[:danger] = "他人のデータは観覧できません"
      redirect_to(root_url) 
    end
  end
  
  def instructor_user
    redirect_to(root_url) unless current_user.instructor?
  end
  
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
  
  def admin_user_show
    redirect_to users_url if current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_time(datetime)
  format("%.2f", ((datetime.hour * 60) + datetime.min)/60.0)
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :belongs %>
      <%= f.text_field :belongs, class: 'form-control' %>
         
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
      
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<%end%>

app/views/users/attendances_now.html.erb
<h1>出勤中社員一覧</h1>
<table class="table-bordered table-striped table-condensed table-hover">
  <thead>
    <tr>
      <td>社員番号</td>
      <td>名前</td>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <% attendances = Attendance.where(user_id: user.id) %>
    <% attendances.each do |at| %>
    <% if Date.today && at.started_at.present? && at.finished_at.nil? && at.finished_be.nil? %>
    <tr>
      <td><%= user.code %></td>
      <td><%= user.name %></td>
    </tr>
    <%end%>
    <%end%>
    <%end%>
  </tbody>
</table>

app/views/users/edit.html.erb
<% provide(:title, "設定") %>
<% provide(:button_text, "更新する") %>
<h1>アカウント情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title,"基本情報編集") %>

<h1>基本情報の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: update_basic_info_path(params: {id: @user.id})) do |f| %>
      <%= render 'shared/error_messages', object: @user %>
      
      <%= f.label :basic_time %>
      <%= f.time_field :basic_time, class: 'form-control' %>
      
      <%= f.label :work_time %>
      <%= f.time_field :work_time, class: 'form-control' %>
      
      <%= f.submit "更新する", class: "btn btn-primary" %>
    <%end%>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title,'一覧') %>
<h1>ユーザー覧</h1>

<div class="csv">
<%= form_tag({controller: "users", action: "import", method: "post"}, {multipart: true}) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "CSVインポート" , class: "btn btn-primary"%>
<% end %>
</div>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= user.name %><br>
      | <%= link_to "削除", user,method: :delete, data: {confirm: "削除してよろしいですか？"},class: "btn btn-primary" %><br>
      <table class="table-bordered table-striped table-condensed table-hover">
        <tr>
          <td class="text-left">
            <button type="button" class="btn btn-primary" data-toggle="collapse" data-target="#collapse-<%=user.id%>">編集</button>
            <div id="collapse-<%=user.id%>" class="collapse">
              <%= form_for (user) do |f| %>
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
                
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>

                <%= f.label :belongs %>
                <%= f.text_field :belongs, class: 'form-control' %>
                
                <%= f.label :code %>
                <%= f.text_field :code, class: 'form-control' %>
                
                <%= f.label :card_id %>
                <%= f.text_field :card_id, class: 'form-control' %>
         
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
      
                <%= f.label :password_confirmation %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
                
                <%= f.label :basic_time %>
                <%= f.time_field :basic_time, class: 'form-control' %>
      
                <%= f.label :work_time %>
                <%= f.time_field :work_time, class: 'form-control' %>
                
                <%= f.label :finish_time %>
                <%= f.time_field :finish_time, class: 'form-control' %>
                
                <%= f.submit "保存", class: "btn btn-primary" %>
              <%end%><!--form_for-->
            </div>
          </td>
        </tr>
      </table>
    </li>
  <%end%><!--@users-->
<ul>

app/views/users/new.html.erb
<% provide(:title, "新規作成") %>
<% provide(:button_text, '作成する') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title,@user.name) %>
<div>
  <table class="table-bordered table-condensed">
    <tr>
      <td>
        <%= link_to_if(current_user?(@user), "←", user_path(params: {id: @user.id, ftime: @ftime.prev_month}), class: "btn btn-xs btn-primary" ){}%>
          &emsp;<%= @ftime.to_s(:year_month) %> 時間管理表 &emsp;
        <%= link_to_if(current_user?(@user),"→", user_path(params: {id: @user.id, ftime: @ftime.next_month}), class: "btn btn-xs btn-primary"){}%></td>
      <td>
        指定勤務開始時間:<%= format_basic_time(@user.work_time) %><br>
        指定勤務終了時間:<%= format_basic_time(@user.finish_time) %>
        </td>
      <td>基本時間:<%= format_basic_time(@user.basic_time)%></td> 
      <td>初日<%= @ftime.to_s(:date) %></td>
    </tr>
  </table>
  <div class="table2">
  <table class="table-bordered table-condensed">
    <tr>
      <td class="a">所属:<%= @user.belongs %></td>
      <td class="b">氏名: <%=@user.name %></td>
      <td>コード</td>
      <td><%= @user.code %></td>
      <td>出勤日数: <%= @worked_sum %>日</td>
      <td class="c">締め<%= @ltime.to_s(:date) %></td>
    </tr>
  </table>
  </div>
  <% if current_user.instructor?  %>
    <% if @count_overtime > 0 && current_user?(@user) %>
        <%= link_to_if(current_user?(@user), "【残業申請のお知らせ】", receive_overtime_path, class: "red" ,remote: true) {}%>
      <font color="red"><%= @count_overtime %>件の通知があります</font>
    <%else%>
      <%= link_to_if(current_user?(@user), "【残業申請のお知らせ】", receive_overtime_path, remote: true) {}%>
    <%end%><br>
      <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
      
    <% if @count_attendance > 0 && current_user?(@user)%>
      <%= link_to_if(current_user?(@user),"【勤怠変更申請のお知らせ】", receive_attendance_path, class: "red", remote: true){}%>
      <font color="red"><%= @count_attendance %>件の通知があります</font>
    <%else%>
      <%= link_to_if(current_user?(@user),"【勤怠変更申請のお知らせ】", receive_attendance_path, remote: true){}%>
    <%end%><br>
      <div id="user-modal1" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
      
    
      <% if @count_month > 0 && current_user?(@user) %>
        <%= link_to_if(current_user?(@user), "【所属長承認申請のお知らせ】",receive_month_path,class: "red", remote: true ){}%>
        <font color="red"><%= @count_month %>件の通知があります</font>
      <%else%>
        <%= link_to_if(current_user?(@user), "【所属長承認申請のお知らせ】",receive_month_path, remote: true ){}%>
      <%end%>
      <div id="user-modal2" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div><br>
  <%end%>
  
  <% if current_user|| current_user.admin? %>
    <%= link_to_if(current_user?(@user), "CSV", user_path(format: :csv), class: "btn btn-primary"){} %>
    <%= link_to_if(current_user?(@user), "勤怠を編集", edit_attendances_path(@user, @ftime), class: "btn btn-primary"){}%>
    <%= link_to_if(current_user?(@user), "勤怠修正ログ", atlog_path(@user,@ftime), class: "btn btn-primary"){} %>
  <%end%>
  
  <table class="table-bordered table-striped table-condensed table-hover">
    <thead>
    <tr>
      <% if current_user?(@user) %>
        <td rowspan="3">残業申請</td>
      <%end%>
      <td rowspan="3">日付</td>
      <td rowspan="3">曜日</td>
      <td colspan="8">【実績】</td>
      <% if current_user?(@user) %>
        <td colspan="8">所定外勤務</td>
      <%else%>
        <td colspan="5">所定外勤務</td>
      <%end%>
    </tr>
    <tr>
      <td colspan="3">出社</td>
      <td colspan="3">退社</td>
      <td rowspan="2">在社時間</td>
      <td rowspan="2">備考</td>
      <td colspan="2">終了予定時間</td>
      <td rowspan="2">時間外時間</td>
      <td rowspan="2">業務処理内容</td>
      <td rowspan="2">指示者確認㊞</td>
    </tr>
    <tr>
      <td>時</td>
      <td>分</td>
      <td></td>
      <td>時</td>
      <td>分</td>
      <td></td>
      <td>時</td>
      <td>分</td>
    </tr>
    </thead>
  
    <tbody>
      <% @dates.each do |day| %>
        <%= fields_for"attendances[]", day do |af| %>
      <tr>
<!--Modal-->
      <% if current_user?(@user) %>
        <td width="10%"> 
          <button type="button" class="btn btn-primary" data-toggle="modal" 
          data-target="#modal-<%=day.id %>" data-date="<%= day.worked_on.to_s(:date) %>">残業申請</button>
          <div class="modal fade" id="modal-<%=day.id %>" tabindex="-1">
          <div class="modal-dialog" role="document">
           <div class="modal-content">
            <div class="modal-header">
             <h1>【残業申請】</h1>
              <%= form_for(@user, url: update_overtime_path(params: {id: @user.id})) do |f| %>
            </dvi>
            <div class="modal-body">
              <table class = "table-bordered table-striped table-condensed">
                <tr>
                  <td>日付</td>
                  <td>曜日</td>
                  <td>終了予定時間</td>
                  <td>翌日</td>
                  <td>業務処理内容</td>
                  <td>指示者確認㊞</td>
                </tr>
              <tbody>
                <tr>
                  <td class="modal-date"><%= day.worked_on.to_s(:date) %></td>
                  <td>
                    <% week_name = %w[日 月 火 水 木 金 土] %>
                     <% str = week_name[day.worked_on.wday] %>
                    <% if day.worked_on.wday == 0 %>
                      <font color="red"><%=week_name[day.worked_on.wday]%></font>
                    <% elsif day.worked_on.wday == 6 %>
                      <font color="blue"><%=week_name[day.worked_on.wday]%></font>
                    <%else%>
                      <%= str%>
                    <%end%>
                  </td>
                  <td class="modal-date">
                    <div class="time_control">
                      <%= af.time_select :over_time,:default =>day.worked_on, class: "form-control" %>
                    </div>
                  </td>
                  <td>
                    <div class="check_box">
                      <%= f.check_box :box %>
                    </div>
                  </td>
                  <td><div class="text_field"%><%= af.text_field :overtime_note,  class: "form-control" %></div></td>
                  <td><%= af.collection_select :instructor_name,User.where(instructor: true).where.not(id: @user.id),:id,:name%></td>
                </tr>
              </tbody>
            </table>  
          <div class="modal-footer">
            <%= f.submit "変更を送信する", class: "btn btn-primary" %>
          </div>
          <%end%>
         </div>
            </div>
           </div>
          </div>
        </td>
        <%end%>
      <%end%>
<!--Modal終了-->
        <td width="5%"><%=day.worked_on.to_s(:date)%></td>
        <td width ="5%">
         <% week_name = %w[日 月 火 水 木 金 土] %>
         <% str = week_name[day.worked_on.wday] %>
         <% if day.worked_on.wday == 0 %>
           <font color="red"><%=week_name[day.worked_on.wday]%></font>
         <% elsif day.worked_on.wday == 6 %>
           <font color="blue"><%=week_name[day.worked_on.wday]%></font>
          <%else%>
            <%= str%>
         <%end%>
        </td>
<!--【実績】-->
        <td>
          <% if day.approval_at == "承認" && day.started_be.present? %>
            <%= day.started_be.to_s(:hour) %>
          <% elsif  day.started_at.present?%>
            <%= day.started_at.to_s(:hour)%>
          <%end%>
        </td>
        <td>
          <% if day.approval_at == "承認" && day.started_be.present? %>
            <%= day.started_be.ceil_to(15.minutes).to_s(:min) %>
          <% elsif day.started_at.present?%>
            <%= day.started_at.ceil_to(15.minutes).to_s(:min) %>
          <%end%>
        </td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.nil? && current_user?(@user)%>
            <%= button_to "出社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <%end%>
        </td>
        <td>
          <% if day.approval_at == "承認" && day.finished_be.present? %>
            <%= day.finished_be.to_s(:hour) %>
          <% elsif day.finished_at.present?%>
            <%= day.finished_at.to_s(:hour) %>
          <%end%>
        </td>
        <td>
          <% if day.approval_at == "承認" && day.finished_be.present? %>
            <%= day.finished_be.ceil_to(15.minutes).to_s(:min)%>
          <% elsif day.finished_at.present? %>
            <%= day.finished_at.ceil_to(15.minutes).to_s(:min)%>
          <%end%>
        </td>
        <td>
          <% if day.worked_on == Date.today && day.started_at.present? && day.finished_at.nil? && current_user?(@user) %>
            <%= button_to "退社", user_attendances_path(@user), class: "btn btn-xs btn-primary" %>
          <%end%>
        </td>
        <td>
          <% if day.started_at.present? && day.finished_at.present? %>
            <%= working_times(day.started_at.ceil_to(15.minutes), day.finished_at.ceil_to(15.minutes)) %>
            <% seconds = (day.finished_at - day.started_at).to_i %>
            <% @total_seconds = @total_seconds.to_i + seconds %>
          <%end%>
        </td>
        <td><%= day.note %></td>
<!--【所定外勤務】-->
        <td><%= day.over_time.to_s(:hour) if day.over_time.present?%></td>
        <td><%= day.over_time.to_s(:min) if day.over_time.present?%></td>
        <td>
          <% if day.over_time.present?%>
            <%=day.over_time.hour-@user.finish_time.hour%>.<%=(day.over_time.min-@user.finish_time.min).abs%>
          <%end%>
        </td>
        <td><%= day.overtime_note %></td>
        <td>
          <% if day.approval == "承認" || day.approval == "否認" %>
            <%= "残業#{day.approval}" %>
          <% elsif day.over_time.present? %>
            <%= "残業:上長#{day.instructor_name-1}に申請中" %>
          <%end%><br>
          <% if day.approval_at == "承認" || day.approval_at == "否認" %>
            <%= "勤怠#{day.approval_at}"%>
          <% elsif day.started_be.present? %>
            <%= "勤怠:上長#{day.instructor_nameat-1}に申請中" %>
          <%end%>
        </td>
      </tr>
      <%end%>
    </tbody>
<!--AV,合計時間-->
    <tfoot>
      <tr>
        <td colspan = "2"><%= format_basic_time(@user.basic_time).to_f* @worked_sum %></td>
        <td colspan = "6"></td>
        <td><%= working_times_sum(@total_seconds.ceil_to(15.minutes)) unless @total_seconds.nil? %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <% if current_user?(@user) %>
        <td width="15%">
          <%= form_for(@user, url: update_month_path(params: {id: @user.id})) do |f| %>
            <% @dates.each do |day| %>
              <%= fields_for "attendances[]", day do |af| %>
                <% if day.approval_mo == "承認" %>
                  <%= "所属長承認　済" %>
                <%else%>
                  <%= "所属長承認　未"%>
                <%end%>
                <%= af.collection_select :instructor_namemo,User.where(instructor: true).where.not(id: @user.id),:id,:name, :include_blank => true, class: "form-control"%>
                <%= af.date_select :month_date,:discard_day => true, :discard_year => true, class: "form-control"%>
                <%= f.submit "申請", class: "btn btn-primary" %>
              <%end%><!--fields_for-->
            <%break%>
            <%end%><!--day-->
          <%end%><!--fomr_for-->
        </td>
        <%end%>
      </tr>
    </tfoot>
  </table>
    
</div>