config/routes.rb
Rails.application.routes.draw do
  root 'first#home'
  get '/singup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/attendances_now', to: 'users#attendances_now', as: :attendances_now
  patch 'users/:id/attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime #残業申請
  patch 'users/:id/attendances/:id/update_month', to: 'attendances#update_month', as: :update_month #所属長申請
  get 'users/:id/attendances/:id/receive_overtime', to: 'attendances#receive_overtime', as: :receive_overtime#残業申請のお知らせ
  patch 'users/:id/attendances/:id/update_receive', to: 'attendances#update_receive', as: :update_receive #~申請のお知らせ(update)
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances#勤怠を編集
  get 'users/:id/attendances/:date/atlog', to: 'attendances#atlog', as: :atlog#勤怠修正ログ
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances#勤怠を編集(update)
  get 'users/:id/attendances/:id/receive_attendance', to: 'attendances#receive_attendance', as: :receive_attendance #勤怠変更のお知らせ
  patch 'users/:id/attendances/:id/update_receive_attendance', to: 'attendances#update_receive_attendance', as: :update_receive_attendance #勤怠変更のお知らせ
  get 'users/:id/attendances/:id/receive_month', to: 'attendances#receive_month', as: :receive_month#所属長承認のお知らせ
  
  resources :users do
    resources :attendances
  end
  
  resources :bases
  
  resources 'users', only: :index do
    collection { post :import }
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  validates :worked_on, presence: true
  validates :update_box, acceptance: true
  validates :update_boxat, acceptance: true
  validates :update_boxmo, acceptance: true
  
  enum approval: {'なし'=> 0, '申請中'=> 1, '承認'=> 2, '否認'=> 3}, _prefix: true
  enum approval_at: {'なし'=> 0, '申請中'=> 1, '承認'=> 2, '否認'=> 3}, _prefix: true
  enum approval_mo: {'なし'=> 0, '申請中'=> 1, '承認'=> 2, '否認'=> 3}, _prefix: true
  
  validate :finished_at_st_blank
    def finished_at_st_blank
      if started_at.blank? && finished_at.present?
       errors.add(:finished_at, "出勤時間がありません。")
      end
    end
    
    
  validate :finished_at_started_faster
    def finished_at_started_faster
      if  started_at.present? && finished_at.present?
        if started_at > finished_at
          errors.add(:finished_at, "出勤時間の方が早いです。")
        end
      end
    end
  
  validate :finished_be_st_blank
  validate :finished_be_started_faster
  
  def finished_be_st_blank
    errors.add(:started_be, "が必要です") if started_be.blank? && finished_be.present?
  end
  
  def started_be_st_blank
    errors.add(:finished_be, "が必要です") if started_be.present? && finished_be.blank?
  end
    
  def finished_be_started_faster
    if started_be.present? && finished_be.present?
      errors.add(:started_be, "より早い退勤時間は無効です") if started_be > finished_be
    end
  end
end  

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :correct_user, only:[:edit,:atlog]
  before_action :admin_user_show, only: [:edit,:atlog]
  
  def create
    @user = User.find(params[:user_id])
    @attendance = @user.attendances.find_by(worked_on: Date.today)
    if @attendance.started_at.nil?
      @attendance.update_attributes(started_at: current_time)
      flash[:info] = 'おはようございます'
    elsif @attendance.finished_at.nil?
      @attendance.update_attributes(finished_at: current_time)
      flash[:info] = 'おつかれさまでした'
    else
      flash[:danger] = 'トラブルがあり、登録できませんでした。'
    end
    redirect_to @user
  end
  
  
  def edit
    @user = User.find(params[:id])
    @users = User.all
    @instructor = User.where(instructor: true)
    @ftime = Date.parse(params[:date])
    @ltime = @ftime.end_of_month
    @dates = user_attendances_month_date
  end
  
  def atlog
    @user = User.find(params[:id])
    if params[:ftime].nil?
      @ftime = Date.today.beginning_of_month
    else
      @ftime = Date.parse(params[:ftime])
    end
    @ltime = @ftime.end_of_month
    (@ftime..@ltime).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @ftime = Date.parse(params[:date])
    @ltime = @ftime.end_of_month
    @dates =  user_attendances_month_date
  end
  
  def update
    @user = User.find(params[:id])
    @instructor = User.where(instructor: true)
      if instructor_name_nil?
          attendances_params.each do |id, item|
            attendance = Attendance.find(id)
            attendance.update_attributes(item)
          end
        flash[:info] = '勤怠情報を申請しました。記入漏れないか確認してください。'
        redirect_to user_path(@user, params:{first_day: params[:date]})
      else
        flash[:danger] = "上長を選択してください。"
        redirect_to edit_attendances_path(@user, params[:date])
      end
  end
  
  def update_overtime
    @user = User.find(params[:id])
    if overtime_params.each do |id,item|
      ot = Attendance.find(id)
      ot.update_attributes!(item)
      flash[:success] = "残業申請しました"
      redirect_to @user
    end
    else
      render '@user'
    end
  end
  
  def update_month
    @user = User.find(params[:id])
    if month_params.each do |id,item|
      ot = Attendance.find(id)
      ot.update_attributes!(item)
      flash[:success] = "所属長申請しました"
      redirect_to @user
    end
    else
      render '@user'
    end
  end
  
  def update_receive
    @user = User.find(params[:id])
    if receive_params.nil?
      flash[:danger] = "更新対象がありません"
      redirect_to @user
      return
    else
     receive_params.each do |id,item|
     rot = Attendance.find(id)
     rot.update_attributes(item) 
     end
     flash[:info] ="申請中です。チェック漏れがないかご確認ください。"
     redirect_to @user
     return
    end
  end
  
  def receive_overtime
    @user = User.find(params[:id])
    @users = User.all 
    @attendance = Attendance.find(params[:id]) 
    @instructor = User.where(instructor: true) 
     if params[:ftime].nil?
       @ftime = Date.today.beginning_of_month
     else
       @ftime = Date.parse(params[:ftime])
     end
    @ltime = @ftime.end_of_month
    (@ftime..@ltime).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
  end
  
  
  def receive_attendance
    @user = User.find(params[:id])
    @users = User.all 
    @attendance = Attendance.find(params[:id]) 
    @instructor = User.where(instructor: true) 
     if params[:ftime].nil?
       @ftime = Date.today.beginning_of_month
     else
       @ftime = Date.parse(params[:ftime])
     end
    @ltime = @ftime.end_of_month
    (@ftime..@ltime).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
  end
  
  def receive_month
    @user = User.find(params[:id])
    @users = User.all 
    @attendance = Attendance.find(params[:id]) 
    @instructor = User.where(instructor: true) 
     if params[:ftime].nil?
       @ftime = Date.today.beginning_of_month
     else
       @ftime = Date.parse(params[:ftime])
     end
    @ltime = @ftime.end_of_month
    (@ftime..@ltime).each do |day|
      unless @user.attendances.any?{|attendance| attendance.worked_on == day}
        record = @user.attendances.build(worked_on: day)
        record.save
      end
    end
    @dates = user_attendances_month_date
  end
    
  private
  
  def attendances_params
    params.permit(attendances: [:started_be,:finished_be,:note,:instructor_nameat])[:attendances]
  end
  
  def overtime_params
    params.permit(attendances: [:over_time,:overtime_note,:instructor_name])[:attendances]
  end
  
  def month_params
    params.permit(attendances: [:month_date,:instructor_namemo])[:attendances]
  end
  
  def receive_params
    params.permit(attendances: [:approval,:update_box,:approval_at,:update_boxat,:approval_mo,:update_boxmo])[:attendances]
  end
  
  def correct_user
    @user = User.find(params[:id])
    unless current_user?(@user) || current_user.admin? 
      flash[:danger] = "他人のデータは観覧できません"
      redirect_to(root_url) 
    end
  end
  
  def admin_user_show
    redirect_to users_url if current_user.admin?
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  def current_time
    Time.new(
        Time.now.year,
        Time.now.month,
        Time.now.day,
        Time.now.hour,
        Time.now.min,0
        )
  end
  
  def working_times(started_at, finished_at)
    format("%.2f",(((finished_at - started_at)/ 60) / 60))
  end
  
  def overtimes_sub(over_time, finish_time)
    format("%.2f",(((over_time - finish_time)/ 60) / 60))
  end
  
  def working_times_sum(seconds)
    format("%.2f", seconds / 60 / 60.0)
  end
  
  def ftime(date)
    !date.nil? ? Date.parse(date) : Date.current.beginning_of_month
  end

  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @ftime, @ltime).order('worked_on')
  end
  
  def instructor_name_nil?
    attendances = true
    attendances_params.each do |id,item|
      if item[:started_be].present? && item[:finished_be].present? && item[:instructor_nameat].blank?
        attendances = false
      end
    end
    return attendances
  end
end  

app/views/attendances/_create_overtime.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
    <h1>【残業申請】</h1>
      <table class = "table-bordered table-striped table-condensed">
        <tr>
          <td>日付</td>
          <td>曜日</td>
          <td>終了予定時間</td>
          <td>翌日</td>
          <td>業務処理内容</td>
          <td>指示者確認㊞</td>
        </tr>
        <tr>
          <td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
     </table>  
    </div>
  </div>
</div>

app/views/attendances/_receive_attendance.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <%= form_for(@user, url: update_receive_path(params: {id: @user.id})) do |f| %>
        <% @users.each do |user| %>
        <% attendances = Attendance.where(user_id: user.id) %>
        <% attendances.each do |at| %>
        <% if at.instructor_nameat == current_user.id %>
        <% if at.started_be.present? %>
          <% if at.update_boxat.blank? || at.approval_at == "申請中"  %>
              <h1>【<%= user.name %>からの勤怠変更申請】</h1>
              <%break%>
          <%end%>
        <%end%>
        <%end%>
        <%end%>
        <div class="modal-body">
        <% attendances = Attendance.where(user_id: user.id) %>
        <% attendances.each do |at| %>
        <% if at.instructor_nameat == current_user.id %>
          <% if at.started_be.present? %>
          <% if at.update_boxat.blank? || at.approval_at == "申請中" %>
          <table class="table-bordered table-striped table-condensed">
          <tr>
            <td rowspan="3">日付</td>
            <td rowspan="3">曜日</td>
            <td colspan="4">変更前</td>
            <td colspan="4">変更後</td>
            <td rowspan="3">備考</td>
            <td rowspan="3">指示者確認㊞</td>
            <td rowspan="3">変更</td>
            <td rowspan="3">勤怠を確認</td>
          </tr>
          <tr>
            <td colspan="2">出社</td>
            <td colspan="2">退社</td>
            <td colspan="2">出社</td>
            <td colspan="2">退社</td>
          </tr>
          <td>時</td>
          <td>分</td>
          <td>時</td>
          <td>分</td>
          <td>時</td>
          <td>分</td>
          <td>時</td>
          <td>分</td>
          <%break%>
          <%end%>
        <%end%>
        <%end%>
        <%end%>
        <tbody>
          <% attendances.each do |at| %>
          <%= fields_for"attendances[]", at do |af| %>
          <% if at.instructor_nameat == current_user.id %>
          <% if at.started_be.present? %>
          <% if at.update_boxat.blank? || at.approval_at == "申請中" %>
          <tr>
            <td><%= at.worked_on.to_s(:date) %></td>
            <td>
              <% week_name = %w[日 月 火 水 木 金 土] %>
              <% str = week_name[at.worked_on.wday] %>
              <% if at.worked_on.wday == 0 %>
                <font color="red"><%=week_name[at.worked_on.wday]%></font>
              <% elsif at.worked_on.wday == 6 %>
                <font color="blue"><%=week_name[at.worked_on.wday]%></font>
              <%else%>
                <%= str%>
              <%end%>
            </td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><%= at.started_be.to_s(:hour) if at.started_be.present?  %></td>
            <td><%= at.started_be.ceil_to(15.minutes).to_s(:min) if at.started_be.present? %></td>
            <td><%= at.finished_be.to_s(:hour) if at.finished_be.present? %></td>
            <td><%= at.finished_be.ceil_to(15.minutes).to_s(:min) if at.finished_be.present?%></td>
            <td><%= at.note %></td>
            <td><%= af.select :approval_at, Attendance.approvals.keys.to_a ,{} , class: "form-control"%></td>
            <td><%= af.check_box :update_boxat%></td>
            <td><%= link_to "確認",user, class: "btn btn-primary" %></td>
          </tr>
          <%end%>
         <%end%>
         <%end%><!--if-->
         <%end%><!--fields_for--!>
         <%end%><!--atttendance.each-->
        </tbody>
        </table>
        </div><!--modal-body-->
        <%end%><!--@users.each-->
        <div class="modal-footer">
          <div class="overtime_receive_bottun">
            <%= f.submit "変更を送信する", class: "btn btn-primary" %>
          </div><!--bottun-->
        </div><!--modal-footer-->
        <%end%><!--form_for-->
  </div>
</div>

app/views/attendances/_receive_month.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <%= form_for(@user,url: update_receive_path(params: {id: @user.id})) do |f| %>
      <% @users.each do |user| %>
        <% attendances = Attendance.where(user_id: user.id) %>
          <% attendances.each do |at| %>
            <% if at.instructor_namemo == current_user.id %>
              <% if at.update_boxmo.blank? || at.approval_mo == "申請中"  %>
                <h1>【<%= user.name %>からの所属長申請】</h1>
                <%break%>
              <%end%>
          <%end%><!--if-->
        <%end%><!--attendances-->
        <div class="modal-body">
          <% attendances = Attendance.where(user_id: user.id) %>
          <% attendances.each do |at| %>
            <% if at.instructor_namemo == current_user.id %>
              <% if at.update_boxmo.blank? || at.approval_mo == "申請中"  %>
              <table class="table-bordered table-striped table-condensed">
                <tr>
                  <td>月</td>
                  <td>指示者確認㊞</td>
                  <td>変更</td>
                  <td>勤怠を確認する</td>
                </tr>
                <%break%>
              <%end%>
            <%end%><!--if at.instructor_namemo-->
          <%end%><!--attendances.each-->
          <tbody>
            <% attendances.each do |at| %>
              <%= fields_for"attendances[]", at do |af| %>
              <% if at.instructor_namemo == current_user.id %>
              <% if at.update_boxmo.blank? || at.approval_mo == "申請中"  %>
                <tr>
                 <td><%= at.month_date.strftime("%-m月") %></td>
                 <td><%= af.select :approval_mo, Attendance.approvals.keys.to_a ,{} , class: "form-control"%></td>
                 <td><%= af.check_box :update_boxmo%></td>
                 <td><%= link_to "確認",user, class: "btn btn-primary" %></td>
                </tr>
              <%end%>
              <%end%><!--if-->
              <%end%><!--fields_for-->
            <%end%><!--attendances.each-->
          </tbody>
         </table>
        </div><!--modal-body-->
      <%end%><!--@users-->
      <div class="modal-footer">
        <%= f.submit "変更を送信する", class: "btn btn-primary" %>
      </div>
    <%end%><!--form_for-->
  </div>
</div>

app/views/attendances/_receive_overtime.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <%= form_for(@user, url: update_receive_path(params: {id: @user.id})) do |f| %>
      <% @users.each do |user| %>
        <% attendances = Attendance.where(user_id: user.id) %>
        <% attendances.each do |at| %>
        <% if at.instructor_name == current_user.id %>
        <% if at.over_time.present? %>
          <% if at.update_box.blank? || at.approval == "申請中" %>
              <h1>【<%= user.name %>からの残業申請】</h1>
              <%break%>
          <%end%>
        <%end%> 
        <%end%>
        <%end%>
        <div class="modal-body">
        <% attendances = Attendance.where(user_id: user.id) %>
        <% attendances.each do |at| %>
        <% if at.instructor_name == current_user.id %>
        <% if at.over_time.present? %>
          <% if at.update_box.blank? || at.approval == "申請中" %>
          <table class="table-bordered table-striped table-condensed">
          <tr>
            <td>日付</td>
            <td>曜日</td>
            <td>終了予定時間</td>
            <td>指定勤務終了時間</td>
            <td>時間外時間</td>
            <td>業務処理内容</td>
            <td>指示者確認㊞</td>
            <td>変更</td>
            <td>勤怠を確認</td>
          </tr>
          <%break%>
          <%end%>
        <%end%>
        <%end%>
        <%end%>
        <tbody>
          <% attendances.each do |at| %>
          <%= fields_for"attendances[]", at do |af| %>
          <% if at.instructor_name == current_user.id %>
          <% if at.over_time.present?%>
          <% if at.update_box.blank? || at.approval == "申請中" %>
          <tr>
            <td><%= at.worked_on.to_s(:date) %></td>
            <td>
              <% week_name = %w[日 月 火 水 木 金 土] %>
              <% str = week_name[at.worked_on.wday] %>
              <% if at.worked_on.wday == 0 %>
                <font color="red"><%=week_name[at.worked_on.wday]%></font>
              <% elsif at.worked_on.wday == 6 %>
                <font color="blue"><%=week_name[at.worked_on.wday]%></font>
              <%else%>
                <%= str%>
              <%end%>
            </td>
            <td><%= at.over_time.to_s(:hourmin)%></td>
            <td><%= format_basic_time(@user.finish_time) %></td>
            <td><%= at.over_time.hour-@user.finish_time.hour%>.<%=(at.over_time.min-@user.finish_time.min).abs%></td>
            <td><%= at.overtime_note %></td>
            <td><%= af.select :approval, Attendance.approvals.keys.to_a ,{} , class: "form-control"%></td>
            <td><%= af.check_box :update_box%></td>
            <td><%= link_to "確認",user, class: "btn btn-primary" %></td>
          </tr>
          <%end%>
         <%end%>
         <%end%><!--if-->
         <%end%><!--fields_for--!>
         <%end%><!--atttendance.each-->
        </tbody>
        </table>
        </div><!--modal-body-->
        <%end%><!--@users.each-->
        <div class="modal-footer">
          <div class="overtime_receive_bottun">
            <%= f.submit "変更を送信する", class: "btn btn-primary" %>
          </div><!--bottun-->
        </div><!--modal-footer-->
    <%end%><!--form_for-->
  </div><!--content-->
</div><!--dialog-->

app/views/attendances/atlog.html.erb
<h1>勤怠修正ログ</h1>
<table class="table-bordered table-striped table-condensed table-hover">
  <thead>
    <tr>
      <td>日付</td>
      <td>変更前出社時間</td>
      <td>変更前退社時間</td>
      <td>変更後出社時間</td>
      <td>変更後退社時間</td>
      <td>承認者</td>
    </tr>
  </thead>
  <tbody>
    <% @dates.each do |day| %>
      <tr>
        <% if day.started_be.present? && day.approval_at == "承認" %>
        <td><%= day.worked_on.to_s(:date)%></td>
        <td><%= day.started_at.to_s(:hourmin)  if day.started_at.present?%></td>
        <td><%= day.finished_at.to_s(:hourmin) if day.finished_at.present?%></td>
        <td><%= day.started_be.to_s(:hourmin)  if day.started_be.present?%></td>
        <td><%= day.finished_be.to_s(:hourmin) if day.finished_be.present?%></td>
        <td><%= "上長#{day.instructor_nameat-1}" if day.started_be.present?%></td>
        <%end%>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/attendances/edit.html.erb
<% provide(:title,"勤怠編集" ) %>
<div>
  <h1>勤怠編集画面</h1>
  <%= form_for(@user, url: update_attendances_path, method: :patch) do |f| %>
   <table class = "table-bordered table-striped table-condensed">
    <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出勤</th>
        <th>退勤</th>
        <th>翌日</th>
        <th>在社時間</th>
        <th>備考</th>
        <th>指示確認㊞</th>
      </tr>
    </thead>
    <tbody>
      <% @dates.each do |day| %>
       <%= fields_for "attendances[]", day do |af| %>
        <tr>
          <td><%= day.worked_on.to_s(:date) %></td>
          <td>
            <% week_name = %w[日 月 火 水 木 金 土] %>
              <% str = week_name[day.worked_on.wday] %>
             <% if day.worked_on.wday == 0 %>
              <font color="red"><%=week_name[day.worked_on.wday]%></font>
             <% elsif day.worked_on.wday == 6 %>
              <font color="blue"><%=week_name[day.worked_on.wday]%></font>
             <%else%>
               <%= str%>
            <%end%>
          </td>
          <td>
            <div class="time_select_edit">
              <%= af.time_field :started_be,:include_blank => true, class: "form-control" %>
            </div>
          </td>
          <td>
            <div class="time_select_edit">
              <%= af.time_field :finished_be,:include_blank => true, class: "form-control" %>
            </div>
          </td>
          <td>
            <div class="check_box">
              <%= af.check_box :over_time%>
            </div>
          </td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= working_times(day.started_at, day.finished_at) %>
            <%end%>
          </td>
          <td><%= af.text_field :note, class: "form-control" %></td>
          <td><%= af.collection_select :instructor_nameat,User.where(instructor: true).where.not(id: @user.id),:id,:name, :include_blank => true, class: "form-control"%></td>
        </tr>
      <% end %>
      <%end%>
     </tbody>
    </table>
  <div class="btn-attendances-update">
    <%= f.submit "更新", class: "btn btn-primary" %>
    <%= link_to "キャンセル", user_path(@user,params:{ftime: @ftime}), class: "btn btn-default btn-block" %>
  </div>
  <%end%>
</div>

app/views/attendances/receive_attendance.js.erb
$("#user-modal1").html("<%= escape_javascript(render 'receive_attendance') %>")
$("#user-modal1").modal("show")

app/views/attendances/receive_month.js.erb
$("#user-modal2").html("<%= escape_javascript(render 'receive_month') %>")
$("#user-modal2").modal("show")

app/views/attendances/receive_overtime.js.erb
$("#user-modal").html("<%= escape_javascript(render 'receive_overtime') %>")
$("#user-modal").modal("show")