config/routes.rb
Rails.application.routes.draw do
  root 'first#home'
  get '/singup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit-basic-info/:id', to: 'users#edit_basic_info', as: :basic_info
  patch 'update-basic-info', to: 'users#update_basic_info'
  get 'users/attendances_now', to: 'users#attendances_now', as: :attendances_now
  patch 'users/:id/attendances/:id/update_overtime', to: 'attendances#update_overtime', as: :update_overtime #残業申請
  patch 'users/:id/attendances/:id/update_month', to: 'attendances#update_month', as: :update_month #所属長申請
  get 'users/:id/attendances/:id/receive_overtime', to: 'attendances#receive_overtime', as: :receive_overtime#残業申請のお知らせ
  patch 'users/:id/attendances/:id/update_receive', to: 'attendances#update_receive', as: :update_receive #~申請のお知らせ(update)
  get 'users/:id/attendances/:date/edit', to: 'attendances#edit', as: :edit_attendances#勤怠を編集
  get 'users/:id/attendances/:date/atlog', to: 'attendances#atlog', as: :atlog#勤怠修正ログ
  patch 'users/:id/attendances/:date/update', to: 'attendances#update', as: :update_attendances#勤怠を編集(update)
  get 'users/:id/attendances/:id/receive_attendance', to: 'attendances#receive_attendance', as: :receive_attendance #勤怠変更のお知らせ
  patch 'users/:id/attendances/:id/update_receive_attendance', to: 'attendances#update_receive_attendance', as: :update_receive_attendance #勤怠変更のお知らせ
  get 'users/:id/attendances/:id/receive_month', to: 'attendances#receive_month', as: :receive_month#所属長承認のお知らせ
  
  resources :users do
    resources :attendances
  end
  
  resources :bases
  
  resources 'users', only: :index do
    collection { post :import }
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
   <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
   <![endif]-->
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "勤怠システム",root_path,id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "トップへ",current_user %></li>
            <% if logged_in? %>
             <% if current_user.admin?  %>
                <li><%= link_to "ユーザー覧",users_path %></li>
                <li><%= link_to"出勤中社員一覧",attendances_now_path %></li>
                <li><%= link_to "拠点一覧", bases_path %></li>
              <%end%>
              <li class="dropdown" >
                <a href = '#' class="dropdown-toggle" data-toggle = "dropdown">
                  アカウント<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "ユーザー勤怠情報表示", current_user %></li>
                  <li><%= link_to "設定", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "ログアウト",logout_path, method: :delete %>
                  </li>
                </ul>
              </li>
            <%else%>
            <li><%= link_to "ログイン", login_path %></li>
            <%end%>
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <%end%>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>